[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
remappings = [
    "ds-test/=lib/solmate/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "abdk-libraries/=lib/abdk-libraries/"
]
auto_detect_remappings = true
ffi = true
via_ir = true

[fuzz]
runs = 100